# Generated by Django 5.2 on 2025-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_move_pokemon_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='effect',
            field=models.TextField(blank=True, null=True),
        ),
    ]
