# Generated by Django 5.2 on 2025-04-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pokemon_attack_pokemon_defense_pokemon_hp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='generation',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='generation_number',
            field=models.PositiveIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(related_name='pokemons', to='core.ability'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='primary_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_pokemons', to='core.type'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='secondary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_pokemons', to='core.type'),
        ),
    ]
