# Generated by Django 5.2 on 2025-04-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ability_type_pokemon_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='generation_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
