# Generated by Django 5.2 on 2025-04-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pokemon_generation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pokemons/'),
        ),
    ]
