# Generated by Django 5.2 on 2025-05-02 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pokemon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='no_effect_against',
            field=models.ManyToManyField(blank=True, related_name='immune_to', to='core.type'),
        ),
        migrations.AddField(
            model_name='type',
            name='strong_against',
            field=models.ManyToManyField(blank=True, related_name='weak_to', to='core.type'),
        ),
        migrations.AddField(
            model_name='type',
            name='weak_against',
            field=models.ManyToManyField(blank=True, related_name='strong_to', to='core.type'),
        ),
        migrations.AlterField(
            model_name='move',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='core.type'),
        ),
    ]
